package com.yui.model;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_user_id
     *
     * @mbg.generated
     */
    private String adminUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_name
     *
     * @mbg.generated
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_passwd
     *
     * @mbg.generated
     */
    private String adminPasswd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_user_id
     *
     * @return the value of admin.admin_user_id
     *
     * @mbg.generated
     */
    public String getAdminUserId() {
        return adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_user_id
     *
     * @param adminUserId the value for admin.admin_user_id
     *
     * @mbg.generated
     */
    public void setAdminUserId(String adminUserId) {
        this.adminUserId = adminUserId == null ? null : adminUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_name
     *
     * @return the value of admin.admin_name
     *
     * @mbg.generated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_name
     *
     * @param adminName the value for admin.admin_name
     *
     * @mbg.generated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_passwd
     *
     * @return the value of admin.admin_passwd
     *
     * @mbg.generated
     */
    public String getAdminPasswd() {
        return adminPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_passwd
     *
     * @param adminPasswd the value for admin.admin_passwd
     *
     * @mbg.generated
     */
    public void setAdminPasswd(String adminPasswd) {
        this.adminPasswd = adminPasswd == null ? null : adminPasswd.trim();
    }
}